server:
  port: 8080

spring:
  application:
    name: WhereYouAd

  # 데이터베이스 설정
  datasource:
    url: ${DB_URL}           # 예: jdbc:mysql://localhost:3306/whereyouad
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} #이메일 앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT 또는 기타 커스텀 설정 (필요시)
jwt:
  secret: ${JWT_SECRET}
#  expiration: 86400000